# Loading data into StellarGraph from Pandas
# Предобработка данных (из табличных в графовый вид)

> This demo explains how to load data into a form that can be used by the StellarGraph library. [See all other demos](../README.md).

# Установи библиотеку так

In [1]:
!pip install stellargraph[demos]

Collecting stellargraph[demos]
  Downloading https://files.pythonhosted.org/packages/74/78/16b23ef04cf6fb24a7dea9fd0e03c8308a56681cc5efe29f16186210ba04/stellargraph-1.2.1-py3-none-any.whl (435kB)
     |████████████████████████████████| 440kB 1.5MB/s eta 0:00:01
Requirement already satisfied: pandas>=0.24 in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (0.25.1)
Collecting tensorflow>=2.1.0 (from stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/eb/18/374af421dfbe74379a458e58ab40cf46b35c3206ce8e183e28c1c627494d/tensorflow-2.3.1-cp37-cp37m-manylinux2010_x86_64.whl (320.4MB)
     |████████████████████████████████| 320.4MB 124kB/s  eta 0:00:01    |█▎                              | 12.9MB 11.5MB/s eta 0:00:27     |██▏                             | 21.4MB 10.8MB/s eta 0:00:28     |███▏                            | 31.3MB 10.6MB/s eta 0:00:28     |███████                         | 69.4MB 11.0MB/s eta 0:00:23     |████████▊                       | 87.5MB 11.1MB/s eta 0:00:22     |█████████████████████████████   | 291.2MB 7.6MB/s eta 0:00:04     |██████████████████████████████▎ | 303.6MB 12.5MB/s eta 0:00:02     |██████████████████████████████▉ | 308.8MB 10.8MB/s eta 0:00:02
Requirement already satisfied: scipy>=1.1.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (1.3.0)
Collecting gensim>=3.4.0 (from stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/5c/4e/afe2315e08a38967f8a3036bbe7e38b428e9b7a90e823a83d0d49df1adf5/gensim-3.8.3-cp37-cp37m-manylinux1_x86_64.whl (24.2MB)
     |████████████████████████████████| 24.2MB 12.1MB/s eta 0:00:01
Requirement already satisfied: networkx>=2.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (2.3)
Requirement already satisfied: scikit-learn>=0.20 in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (0.21.2)
Requirement already satisfied: matplotlib>=2.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (3.1.0)
Requirement already satisfied: numpy>=1.14 in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (1.16.4)
Collecting rdflib; extra == "demos" (from stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/d0/6b/6454aa1db753c0f8bc265a5bd5c10b5721a4bb24160fb4faf758cf6be8a1/rdflib-5.0.0-py3-none-any.whl (231kB)
     |████████████████████████████████| 235kB 13.9MB/s eta 0:00:01
Requirement already satisfied: seaborn; extra == "demos" in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (0.9.0)
Requirement already satisfied: numba; extra == "demos" in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (0.44.1)
Collecting mplleaflet==0.0.5; extra == "demos" (from stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/05/b3/e68ff575ef0872e096878c75f602e76b06ca44d7038d69d867c7b800745b/mplleaflet-0.0.5.tar.gz
Requirement already satisfied: jupyter; extra == "demos" in /home/tim/anaconda3/lib/python3.7/site-packages (from stellargraph[demos]) (1.0.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->stellargraph[demos]) (2.8.0)
Requirement already satisfied: pytz>=2017.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from pandas>=0.24->stellargraph[demos]) (2019.1)
Requirement already satisfied: absl-py>=0.7.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (0.10.0)
Collecting gast==0.3.3 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/d6/84/759f5dd23fec8ba71952d97bcc7e2c9d7d63bdc582421f3cd4be845f0c98/gast-0.3.3-py2.py3-none-any.whl
Collecting astunparse==1.6.3 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/8a/48/a76be51647d0eb9f10e2a4511bf3ffb8cc1e6b14e9e4fab46173aa79f981/termcolor-1.1.0.tar.gz
Requirement already satisfied: wrapt>=1.11.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (1.11.2)
Requirement already satisfied: tensorboard<3,>=2.3.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (2.3.0)
Requirement already satisfied: grpcio>=1.8.6 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (1.26.0)
Collecting tensorflow-estimator<2.4.0,>=2.3.0 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/e9/ed/5853ec0ae380cba4588eab1524e18ece1583b65f7ae0e97321f5ff9dfd60/tensorflow_estimator-2.3.0-py2.py3-none-any.whl (459kB)
     |████████████████████████████████| 460kB 12.4MB/s eta 0:00:01
Requirement already satisfied: wheel>=0.26 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (0.33.4)
Requirement already satisfied: opt-einsum>=2.3.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (3.3.0)
Requirement already satisfied: six>=1.12.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (1.12.0)
Collecting google-pasta>=0.1.8 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/a3/de/c648ef6835192e6e2cc03f40b19eeda4382c49b5bafb43d88b931c4c74ac/google_pasta-0.2.0-py3-none-any.whl (57kB)
     |████████████████████████████████| 61kB 14.6MB/s eta 0:00:01
Collecting h5py<2.11.0,>=2.10.0 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/3f/c0/abde58b837e066bca19a3f7332d9d0493521d7dd6b48248451a9e3fe2214/h5py-2.10.0-cp37-cp37m-manylinux1_x86_64.whl (2.9MB)
     |████████████████████████████████| 2.9MB 12.5MB/s eta 0:00:01
Collecting keras-preprocessing<1.2,>=1.1.1 (from tensorflow>=2.1.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/79/4c/7c3275a01e12ef9368a892926ab932b33bb13d55794881e3573482b378a7/Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42kB)
     |████████████████████████████████| 51kB 8.1MB/s  eta 0:00:01
Requirement already satisfied: protobuf>=3.9.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorflow>=2.1.0->stellargraph[demos]) (3.13.0)
Collecting smart-open>=1.8.1 (from gensim>=3.4.0->stellargraph[demos])
  Downloading https://files.pythonhosted.org/packages/11/9a/ba2d5f67f25e8d5bbf2fcec7a99b1e38428e83cb715f64dd179ca43a11bb/smart_open-3.0.0.tar.gz (113kB)
     |████████████████████████████████| 122kB 11.9MB/s eta 0:00:01
Requirement already satisfied: decorator>=4.3.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from networkx>=2.2->stellargraph[demos]) (4.4.0)
Requirement already satisfied: joblib>=0.11 in /home/tim/anaconda3/lib/python3.7/site-packages (from scikit-learn>=0.20->stellargraph[demos]) (0.13.2)
Requirement already satisfied: cycler>=0.10 in /home/tim/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2->stellargraph[demos]) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2->stellargraph[demos]) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from matplotlib>=2.2->stellargraph[demos]) (2.4.0)
Requirement already satisfied: isodate in /home/tim/anaconda3/lib/python3.7/site-packages (from rdflib; extra == "demos"->stellargraph[demos]) (0.6.0)
Requirement already satisfied: llvmlite>=0.29.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from numba; extra == "demos"->stellargraph[demos]) (0.29.0)
Requirement already satisfied: jinja2 in /home/tim/anaconda3/lib/python3.7/site-packages (from mplleaflet==0.0.5; extra == "demos"->stellargraph[demos]) (2.10.1)

Requirement already satisfied: jupyter-console in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter; extra == "demos"->stellargraph[demos]) (6.0.0)
Requirement already satisfied: qtconsole in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter; extra == "demos"->stellargraph[demos]) (4.5.1)
Requirement already satisfied: notebook in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter; extra == "demos"->stellargraph[demos]) (6.0.0)
Requirement already satisfied: nbconvert in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter; extra == "demos"->stellargraph[demos]) (5.5.0)
Requirement already satisfied: ipykernel in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter; extra == "demos"->stellargraph[demos]) (5.1.1)
Requirement already satisfied: ipywidgets in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter; extra == "demos"->stellargraph[demos]) (7.5.0)
Requirement already satisfied: requests<3,>=2.21.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (2.22.0)
Requirement already satisfied: markdown>=2.6.8 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (3.3.2)
Requirement already satisfied: setuptools>=41.0.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (41.0.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (1.7.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (0.4.1)
Requirement already satisfied: werkzeug>=0.11.15 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (0.15.4)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/tim/anaconda3/lib/python3.7/site-packages (from tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (1.22.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/tim/anaconda3/lib/python3.7/site-packages (from jinja2->mplleaflet==0.0.5; extra == "demos"->stellargraph[demos]) (1.1.1)
Requirement already satisfied: jupyter_client in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (5.3.1)
Requirement already satisfied: ipython in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (7.6.1)
Requirement already satisfied: prompt_toolkit<2.1.0,>=2.0.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (2.0.9)
Requirement already satisfied: pygments in /home/tim/anaconda3/lib/python3.7/site-packages (from jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (2.4.2)
Requirement already satisfied: traitlets in /home/tim/anaconda3/lib/python3.7/site-packages (from qtconsole->jupyter; extra == "demos"->stellargraph[demos]) (4.3.2)
Requirement already satisfied: ipython-genutils in /home/tim/anaconda3/lib/python3.7/site-packages (from qtconsole->jupyter; extra == "demos"->stellargraph[demos]) (0.2.0)
Requirement already satisfied: jupyter-core in /home/tim/anaconda3/lib/python3.7/site-packages (from qtconsole->jupyter; extra == "demos"->stellargraph[demos]) (4.5.0)
Requirement already satisfied: prometheus-client in /home/tim/anaconda3/lib/python3.7/site-packages (from notebook->jupyter; extra == "demos"->stellargraph[demos]) (0.7.1)
Requirement already satisfied: terminado>=0.8.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from notebook->jupyter; extra == "demos"->stellargraph[demos]) (0.8.2)
Requirement already satisfied: pyzmq>=17 in /home/tim/anaconda3/lib/python3.7/site-packages (from notebook->jupyter; extra == "demos"->stellargraph[demos]) (18.0.0)
Requirement already satisfied: nbformat in /home/tim/anaconda3/lib/python3.7/site-packages (from notebook->jupyter; extra == "demos"->stellargraph[demos]) (4.4.0)
Requirement already satisfied: Send2Trash in /home/tim/anaconda3/lib/python3.7/site-packages (from notebook->jupyter; extra == "demos"->stellargraph[demos]) (1.5.0)
Requirement already satisfied: tornado>=5.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from notebook->jupyter; extra == "demos"->stellargraph[demos]) (6.0.3)
Requirement already satisfied: bleach in /home/tim/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (3.1.0)
Requirement already satisfied: entrypoints>=0.2.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (0.3)
Requirement already satisfied: testpath in /home/tim/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (0.4.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (1.4.2)
Requirement already satisfied: mistune>=0.8.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (0.8.4)
Requirement already satisfied: defusedxml in /home/tim/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (0.6.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from ipywidgets->jupyter; extra == "demos"->stellargraph[demos]) (3.5.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (1.24.2)
Requirement already satisfied: idna<2.9,>=2.5 in /home/tim/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/tim/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/tim/anaconda3/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (2019.9.11)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/tim/anaconda3/lib/python3.7/site-packages (from markdown>=2.6.8->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (0.17)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (1.3.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (4.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/tim/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /home/tim/anaconda3/lib/python3.7/site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (4.6)
Requirement already satisfied: backcall in /home/tim/anaconda3/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (0.1.0)
Requirement already satisfied: pickleshare in /home/tim/anaconda3/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (0.7.5)
Requirement already satisfied: jedi>=0.10 in /home/tim/anaconda3/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (0.13.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in /home/tim/anaconda3/lib/python3.7/site-packages (from ipython->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (4.7.0)
Requirement already satisfied: wcwidth in /home/tim/anaconda3/lib/python3.7/site-packages (from prompt_toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (0.1.7)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /home/tim/anaconda3/lib/python3.7/site-packages (from nbformat->notebook->jupyter; extra == "demos"->stellargraph[demos]) (3.0.1)
Requirement already satisfied: webencodings in /home/tim/anaconda3/lib/python3.7/site-packages (from bleach->nbconvert->jupyter; extra == "demos"->stellargraph[demos]) (0.5.1)
Requirement already satisfied: zipp>=0.5 in /home/tim/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->markdown>=2.6.8->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (0.5.1)
Requirement already satisfied: oauthlib>=3.0.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (3.1.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/tim/anaconda3/lib/python3.7/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow>=2.1.0->stellargraph[demos]) (0.4.8)
Requirement already satisfied: parso>=0.3.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (0.5.0)

Requirement already satisfied: ptyprocess>=0.5 in /home/tim/anaconda3/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython->jupyter-console->jupyter; extra == "demos"->stellargraph[demos]) (0.6.0)
Requirement already satisfied: attrs>=17.4.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter; extra == "demos"->stellargraph[demos]) (19.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/tim/anaconda3/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter; extra == "demos"->stellargraph[demos]) (0.14.11)
Building wheels for collected packages: mplleaflet, termcolor, smart-open
  Building wheel for mplleaflet (setup.py) ... done
  Created wheel for mplleaflet: filename=mplleaflet-0.0.5-cp37-none-any.whl size=28556 sha256=53cd69c85a415660e94401e2abd07889fac400d8477a9a78aac6816a0901eadb
  Stored in directory: /home/tim/.cache/pip/wheels/bf/fd/0b/0513de62c339c4a56e2234aa42a5d06e6660a4446fdae7b796
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-cp37-none-any.whl size=4831 sha256=c794454b9e40ade9c08e5eeb92f10b3ff97b1e847e3d4ce485f90677e4fce99b
  Stored in directory: /home/tim/.cache/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6
  Building wheel for smart-open (setup.py) ... done
  Created wheel for smart-open: filename=smart_open-3.0.0-cp37-none-any.whl size=107099 sha256=554470c0bac0b9286d31244418e9fe53493b838fdaf78e118d62e7b5b01569d2
  Stored in directory: /home/tim/.cache/pip/wheels/18/88/7c/f06dabd5e9cabe02d2269167bcacbbf9b47d0c0ff7d6ebcb78
Successfully built mplleaflet termcolor smart-open
Installing collected packages: gast, astunparse, termcolor, tensorflow-estimator, google-pasta, h5py, keras-preprocessing, tensorflow, smart-open, gensim, rdflib, mplleaflet, stellargraph
  Found existing installation: h5py 2.9.0
    Uninstalling h5py-2.9.0:
      Successfully uninstalled h5py-2.9.0
Successfully installed astunparse-1.6.3 gast-0.3.3 gensim-3.8.3 google-pasta-0.2.0 h5py-2.10.0 keras-preprocessing-1.1.2 mplleaflet-0.0.5 rdflib-5.0.0 smart-open-3.0.0 stellargraph-1.2.1 tensorflow-2.3.1 tensorflow-estimator-2.3.0 termcolor-1.1.0

# Ура. теперь все заработает.

<table><tr><td>Run the latest release of this notebook:</td><td><a href="https://mybinder.org/v2/gh/stellargraph/stellargraph/master?urlpath=lab/tree/demos/basics/loading-pandas.ipynb" alt="Open In Binder" target="_parent"><img src="https://mybinder.org/badge_logo.svg"/></a></td><td><a href="https://colab.research.google.com/github/stellargraph/stellargraph/blob/master/demos/basics/loading-pandas.ipynb" alt="Open In Colab" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg"/></a></td></tr></table>

[The StellarGraph library](https://github.com/stellargraph/stellargraph) supports loading graph information from Pandas. [Pandas](https://pandas.pydata.org) is a library for working with data frames.

This is a great way to load data that offers a good balance between performance and convenience.

The StellarGraph library supports many deep machine learning (ML) algorithms on [graphs](https://en.wikipedia.org/wiki/Graph_%28discrete_mathematics%29). A graph consists of a set of *nodes* connected by *edges*, potentially with information associated with each node and edge. Any task using the StellarGraph library needs data to be loaded into an instance of the `StellarGraph` class. This class stores the graph structure (the nodes and the edges between them), as well as information about them:

- *node types* and *edge types*: a class or category to which the nodes and edges belong, dictating what features are available on a node, and potentially signifying some sort of semantic meaning (this is different to machine learning label for a node)
- *node features* and *edge features*: vectors of numbers associated with each node or edge
- *edge weights*: a number associated with each edge

All of these are optional, because they have sensible defaults if they're not relevant to the task at hand.

This notebook walks through loading several kinds of graphs using Pandas. Pandas is a reasonably efficient form of loading, that is convenient for preprocessing.

- homogeneous graph without features (a homogeneous graph is one with only one type of node and one type of edge)
- homogeneous graph with node/edge features
- homogeneous graph with edge weights
- directed graphs (a graph is directed if edges have a "start" and "end" nodes, instead of just connecting two nodes)
- heterogeneous graphs (more than one node type and/or more than one edge type) with and without node/edge features or edge weights, this includes knowledge graphs
- real data: homogeneous graph from CSV files (an example of reading data from files and doing some preprocessing)

> StellarGraph supports loading data from many sources with all sorts of data preprocessing, via [Pandas](https://pandas.pydata.org) DataFrames, [NumPy](https://www.numpy.org) arrays, [Neo4j](https://neo4j.com) and [NetworkX](https://networkx.github.io) graphs. See [all loading demos](README.md) for more details.

The [documentation](https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.StellarGraph) for the `StellarGraph` class includes a compressed reminder of everything discussed in this file, as well as explanations of all of the parameters.

The `StellarGraph` class is available at the top level of the `stellargraph` library:

In [1]:
# install StellarGraph if running on Google Colab
import sys
if 'google.colab' in sys.modules:
  %pip install -q stellargraph[demos]==1.2.1

In [2]:
# verify that we're using the correct version of StellarGraph for this notebook
import stellargraph as sg

try:
    sg.utils.validate_notebook_version("1.2.1")
except AttributeError:
    raise ValueError(
        f"This notebook requires StellarGraph version 1.2.1, but a different version {sg.__version__} is installed.  Please see <https://github.com/stellargraph/stellargraph/issues/1172>."
    ) from None

In [3]:
#!pip install stellargraph[demos]

In [4]:
from stellargraph import StellarGraph

## Loading from anything, via Pandas

Pandas DataFrames are tables of data that can be created from [many input sources](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html), such as [CSV files](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) and [SQL databases](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html). StellarGraph builds on this power by allowing construction from these DataFrames.

In [5]:
import pandas as pd

Pandas is widely supported by other libraries and products, like [scikit-learn](http://scikit-learn.github.io/stable), and thus a user of StellarGraph gets to benefit from these easily too.

## Homogeneous graph without features

We'll start with a homogeneous graph without any node features. This means the graph consists of only nodes and edges without any information other than a unique identifier.

The basic form of constructing a `StellarGraph` is passing in an edge `DataFrame` with two columns (`source` and `target`), where each row represents a pair of nodes that are connected. Let's construct a `StellarGraph` representing a square with a diagonal:

```
a -- b
| \  |
|  \ |
d -- c
```

We'll start with a synthetic DataFrame defined in code here (there's some examples later of reading DataFrames from files).

Each row represents a connection: for instance, the first one is the edge from `a` to `b`.

In [6]:
square_edges = pd.DataFrame(
    {"source": ["a", "b", "c", "d", "a"], "target": ["b", "c", "d", "a", "c"]}
)
square_edges

  source target
0      a      b
1      b      c
2      c      d
3      d      a
4      a      c

Given our edges, we can create a `StellarGraph` directly:

In [7]:
square = StellarGraph(edges=square_edges)

The `info` method ([docs](https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.StellarGraph.info)) gives a high-level summary of a `StellarGraph`:

In [8]:
print(square.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [5]
        Weights: all 1 (default)
        Features: none

On this square, it tells us that there's 4 nodes of type `default` (a homogeneous graph still has node and edge types, but they default to `default`), with no features, and one type of edge that touches it. It also tells us that there's 5 edges of type `default` that go between nodes of type `default`. This matches what we expect: it's a graph with 4 nodes and 5 edges and one type of each.

The default node type and edge types can be set using the `node_type_default` and `edge_type_default` parameters to `StellarGraph(...)`:

In [9]:
square_named = StellarGraph(
    edges=square_edges, node_type_default="corner", edge_type_default="line"
)
print(square_named.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  corner: [4]
    Features: none
    Edge types: corner-line->corner

 Edge types:
    corner-line->corner: [5]
        Weights: all 1 (default)
        Features: none

The names of the columns used for the edges can be controlled with the `source_column` and `target_column` parameters to `StellarGraph(...)`. For instance, maybe our graph comes from a file with `first` and `second` columns:

In [10]:
square_edges_first_second = square_edges.rename(
    columns={"source": "first", "target": "second"}
)
square_edges_first_second

  first second
0     a      b
1     b      c
2     c      d
3     d      a
4     a      c

In [11]:
square_first_second = StellarGraph(
    edges=square_edges_first_second, source_column="first", target_column="second"
)
print(square_first_second.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [5]
        Weights: all 1 (default)
        Features: none

## Homogeneous graph with features

For many real-world problems, we have more than just graph structure: we have information about the nodes and edges. For instance, we might have a graph of academic papers (nodes) and how they cite each other (edges): we might have information about the nodes such as the authors and the publication year, and even the abstract or full paper contents. If we're doing a machine learning task, it can be useful to feed this information into models. The `StellarGraph` class supports this using a Pandas DataFrame: each row corresponds to a feature vector for a node or edge.

### Node features

Let's imagine the nodes have two features, which might be their coordinates, or maybe some other piece of information. We'll continue using synthetic DataFrames, but these could easily be read from a file. (There's an example in the "Real data: Homogeneous graph from CSV files" section at the end of this notebook.)

In [12]:
square_node_data = pd.DataFrame(
    {"x": [1, 2, 3, 4], "y": [-0.2, 0.3, 0.0, -0.5]}, index=["a", "b", "c", "d"]
)
square_node_data

   x    y
a  1 -0.2
b  2  0.3
c  3  0.0
d  4 -0.5

`StellarGraph` uses the index of the DataFrame as the connection between a node and a row of the DataFrame. Notice that the `square_features` DataFrame has `a`, ..., `d` as its index, matching the identifiers used in the edges.

We've now got all the right node data, in addition to the edges from before, so now we can create a `StellarGraph`.

In [13]:
square_node_features = StellarGraph(square_node_data, square_edges)
print(square_node_features.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: float32 vector, length 2
    Edge types: default-default->default

 Edge types:
    default-default->default: [5]
        Weights: all 1 (default)
        Features: none

Notice the output of `info` now says that the nodes of the `default` type have 2 features.

We can also give the node and edge types helpful names, using either the `node_type_default`/`edge_type_default` parameters we saw before, or by passing the DataFrames in with a dictionary, where the key is the name of the type.

In [14]:
square_named_node_features = StellarGraph(
    {"corner": square_node_data}, {"line": square_edges}
)
print(square_named_node_features.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  corner: [4]
    Features: float32 vector, length 2
    Edge types: corner-line->corner

 Edge types:
    corner-line->corner: [5]
        Weights: all 1 (default)
        Features: none

### Edge features

Edges can have features in the same way as nodes. Any columns that don't have a special meaning are taken as feature vector elements. This means that the source and target columns are not included in the feature vectors (nor are the weight or edge type columns, that are discussed later).

Let's imagine the edges have 3 features each.

In [15]:
square_edge_data = pd.DataFrame(
    {
        "source": ["a", "b", "c", "d", "a"],
        "target": ["b", "c", "d", "a", "c"],
        "A": [-1, 2, -3, 4, -5],
        "B": [0.4, 0.1, 0.9, 0, 0.9],
        "C": [12, 34, 56, 78, 90],
    }
)
square_edge_data

  source target  A    B   C
0      a      b -1  0.4  12
1      b      c  2  0.1  34
2      c      d -3  0.9  56
3      d      a  4  0.0  78
4      a      c -5  0.9  90

In [16]:
square_named_features = StellarGraph(
    {"corner": square_node_data}, {"line": square_edge_data}
)
print(square_named_features.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  corner: [4]
    Features: float32 vector, length 2
    Edge types: corner-line->corner

 Edge types:
    corner-line->corner: [5]
        Weights: all 1 (default)
        Features: float32 vector, length 3

Notice the output of `info` now says that the edges of the `line` type have 3 features, in addition to the 2 features for each node of type `corner`.

## Homogeneous graph with edge weights

Some algorithms can understand edge weights, which can be used as a measure of the strength of the connection, or a measure of distance between nodes. A `StellarGraph` instance can have weighted edges, by including a `weight` column in the DataFrame of edges.

We'll continue with the synthetic square example, by adding that extra `weight` column into the DataFrame. This column might be part of the data naturally, or it might need to be computed. Either of these is fine with Pandas: in the first case, it can be loaded at the same time as loading the source and target information, and in the second, the full power of Pandas is available to compute it (such as manipulating other information associated with the edge DataFrame, or even by comparing the nodes at each end).

In [17]:
square_weighted_edges = pd.DataFrame(
    {
        "source": ["a", "b", "c", "d", "a"],
        "target": ["b", "c", "d", "a", "c"],
        "weight": [1.0, 0.2, 3.4, 5.67, 1.0],
    }
)
square_weighted_edges

  source target  weight
0      a      b    1.00
1      b      c    0.20
2      c      d    3.40
3      d      a    5.67
4      a      c    1.00

In [18]:
square_weighted = StellarGraph(edges=square_weighted_edges)
print(square_weighted.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-default->default

 Edge types:
    default-default->default: [5]
        Weights: range=[0.2, 5.67], mean=2.254, std=2.25534
        Features: none

Notice the output of `info` now shows additional information about edge weights.

Edges weights can be used with node and edge features; for instance, we create a similar graph to the last graph in the "Homogeneous graph with features" section that has our edge weights:

In [19]:
square_weighted_edge_data = pd.DataFrame(
    {
        "source": ["a", "b", "c", "d", "a"],
        "target": ["b", "c", "d", "a", "c"],
        "weight": [1.0, 0.2, 3.4, 5.67, 1.0],
        "A": [-1, 2, -3, 4, -5],
        "B": [0.4, 0.1, 0.9, 0, 0.9],
        "C": [12, 34, 56, 78, 90],
    }
)
square_weighted_edge_data

  source target  weight  A    B   C
0      a      b    1.00 -1  0.4  12
1      b      c    0.20  2  0.1  34
2      c      d    3.40 -3  0.9  56
3      d      a    5.67  4  0.0  78
4      a      c    1.00 -5  0.9  90

In [20]:
square_features_weighted = StellarGraph(
    {"corner": square_node_data}, {"line": square_weighted_edge_data}
)
print(square_features_weighted.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  corner: [4]
    Features: float32 vector, length 2
    Edge types: corner-line->corner

 Edge types:
    corner-line->corner: [5]
        Weights: range=[0.2, 5.67], mean=2.254, std=2.25534
        Features: float32 vector, length 3

## Directed graphs

Some graphs have edge directions, where going from source to target has a different meaning to going from target to source.

A directed graph can be created by using the `StellarDiGraph` class instead of the `StellarGraph` one. The construction is almost identical, and we can reuse any of the DataFrames that we created in the sections above. For instance, continuing from the previous cell, we can have a directed homogeneous graph with node features and edge weights.

In [21]:
from stellargraph import StellarDiGraph

square_features_weighted_directed = StellarDiGraph(
    {"corner": square_node_data}, {"line": square_weighted_edge_data}
)
print(square_features_weighted_directed.info())

StellarDiGraph: Directed multigraph
 Nodes: 4, Edges: 5

 Node types:
  corner: [4]
    Features: float32 vector, length 2
    Edge types: corner-line->corner

 Edge types:
    corner-line->corner: [5]
        Weights: range=[0.2, 5.67], mean=2.254, std=2.25534
        Features: float32 vector, length 3

Everything discussed about `StellarGraph` in this file also works with `StellarDiGraph`, including parameters like `node_type_default` and `source_column`.

## Heterogeneous graphs

Some graphs have multiple types of nodes and multiple types of edges.

For example, an academic citation network that includes authors might have `wrote` edges connecting `author` nodes to `paper` nodes, in addition to the `cites` edges between `paper` nodes. There could be `supervised` edges between `author`s ([example](https://academictree.org)) too, or any number of additional node and edge types. A knowledge graph (aka RDF, triple stores or knowledge base) is an extreme form of an heterogeneous graph, with dozens, hundreds or even thousands of edge (or relation) types. Typically in a knowledge graph, edges and their types represent the information associated with a node, rather than node features.

`StellarGraph` supports all forms of heterogeneous graphs.

A heterogeneous `StellarGraph` can be constructed in a similar way to a homogeneous graph, except we pass a dictionary with multiple elements instead of a single element like we did for the Cora examples in the "homogeneous graph with features" section and others above. For a heterogeneous graph, a dictionary has to be passed; passing a single DataFrame does not work.

Let's return to the square graph from earlier:

```
a -- b
| \  |
|  \ |
d -- c
```

### Multiple node types

Suppose `a` is of type `foo`, and no features, but `b`, `c` and `d` are of type `bar` and have two features each, e.g. for `b`, `y = 0.4, z = 100`. Since the features are different shapes (`a` has zero), they need to be modeled as different types, with separate `DataFrame`s.

In [22]:
square_foo = pd.DataFrame(index=["a"])
square_foo

Empty DataFrame
Columns: []
Index: [a]

In [23]:
square_bar = pd.DataFrame(
    {"y": [0.4, 0.1, 0.9], "z": [100, 200, 300]}, index=["b", "c", "d"]
)
square_bar

     y    z
b  0.4  100
c  0.1  200
d  0.9  300

We have the information for the two node types `foo` and `bar` in separate DataFrames, so we can now put them in a dictionary to create a `StellarGraph`. Notice that `info()` is now reporting multiple node types, as well as information specific to each.

In [24]:
square_foo_and_bar = StellarGraph({"foo": square_foo, "bar": square_bar}, square_edges)
print(square_foo_and_bar.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  bar: [3]
    Features: float32 vector, length 2
    Edge types: bar-default->bar, bar-default->foo
  foo: [1]
    Features: none
    Edge types: foo-default->bar

 Edge types:
    bar-default->foo: [3]
        Weights: all 1 (default)
        Features: none
    bar-default->bar: [2]
        Weights: all 1 (default)
        Features: none

Node IDs (the DataFrame index) needs to be unique across all types. For example, renaming the `a` corner to `b` like `square_foo_overlap` in the next cell, is not accepted and a `StellarGraph(...)` call will throw an error

In [25]:
square_foo_overlap = pd.DataFrame({"x": [-1]}, index=["b"])
square_foo_overlap

   x
b -1

In [26]:
# Uncomment to see the error
# StellarGraph({"foo": square_foo_overlap, "bar": square_bar}, square_edges)

If the node IDs aren't unique across types, one way to make them unique is to add a string prefix. You'll need to add the same prefix to the node IDs used in the edges too. Adding a prefix can be done by replacing the index:

In [27]:
square_foo_overlap_prefix = square_foo_overlap.set_index(
    "foo-" + square_foo_overlap.index.astype(str)
)
square_foo_overlap_prefix

       x
foo-b -1

In [28]:
square_bar_prefix = square_bar.set_index("bar-" + square_bar.index.astype(str))
square_bar_prefix

         y    z
bar-b  0.4  100
bar-c  0.1  200
bar-d  0.9  300

### Multiple edge types: type column

Graphs with multiple edge types can be simpler. Since there are often no features on the edges, we can pass a DataFrame with an additional column for the type, specifying it via the `edge_type_column` parameter. If there are features on the edges, multiple edge types can also be created in the same way as multiple node types, by passing with a dictionary of DataFrames.

For example, suppose the edges in our square graph have types based on their orientation.

In [29]:
square_edges_types = square_edges.assign(
    orientation=["horizontal", "vertical", "horizontal", "vertical", "diagonal"]
)
square_edges_types

  source target orientation
0      a      b  horizontal
1      b      c    vertical
2      c      d  horizontal
3      d      a    vertical
4      a      c    diagonal

In [30]:
square_orientation = StellarGraph(
    edges=square_edges_types, edge_type_column="orientation"
)
print(square_orientation.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-diagonal->default, default-horizontal->default, default-vertical->default

 Edge types:
    default-vertical->default: [2]
        Weights: all 1 (default)
        Features: none
    default-horizontal->default: [2]
        Weights: all 1 (default)
        Features: none
    default-diagonal->default: [1]
        Weights: all 1 (default)
        Features: none

Edge weights are supported, in the same way as a homogeneous graph above, with a `weight` column:

In [31]:
square_edges_types_weighted = square_edges_types.assign(weight=[1.0, 0.2, 3.4, 5.67, 1.0])
square_edges_types_weighted

  source target orientation  weight
0      a      b  horizontal    1.00
1      b      c    vertical    0.20
2      c      d  horizontal    3.40
3      d      a    vertical    5.67
4      a      c    diagonal    1.00

In [32]:
square_orientation_weighted = StellarGraph(
    edges=square_edges_types_weighted, edge_type_column="orientation"
)
print(square_orientation_weighted.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-diagonal->default, default-horizontal->default, default-vertical->default

 Edge types:
    default-vertical->default: [2]
        Weights: range=[0.2, 5.67], mean=2.935, std=3.86787
        Features: none
    default-horizontal->default: [2]
        Weights: range=[1, 3.4], mean=2.2, std=1.69706
        Features: none
    default-diagonal->default: [1]
        Weights: all 1 (default)
        Features: none

### Multiple edge types: edge features

As mentioned above, if there are multiple edge types and the edges have edge features, one will typically need to pass a dictionary of DataFrames similar to multiple node types. The features of each type can be different.

Note: Edges also have IDs (the DataFrame index, like nodes), and they need to be unique across all edge types.

In [33]:
square_edges_horizontal = pd.DataFrame(
    {"source": ["a", "c"], "target": ["b", "d"], "A": [-1, -3]}, index=[0, 2]
)
square_edges_vertical = pd.DataFrame(
    {"source": ["b", "d"], "target": ["c", "a"], "B": [0.1, 0], "C": [34, 78]},
    index=[1, 3],
)
square_edges_diagonal = pd.DataFrame({"source": ["a"], "target": ["c"]}, index=[4])

# example:
square_edges_horizontal

  source target  A
0      a      b -1
2      c      d -3

In [34]:
square_orientation_separate = StellarGraph(
    edges={
        "horizontal": square_edges_horizontal,
        "vertical": square_edges_vertical,
        "diagonal": square_edges_diagonal,
    },
)
print(square_orientation_separate.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-diagonal->default, default-horizontal->default, default-vertical->default

 Edge types:
    default-vertical->default: [2]
        Weights: all 1 (default)
        Features: float32 vector, length 2
    default-horizontal->default: [2]
        Weights: all 1 (default)
        Features: float32 vector, length 1
    default-diagonal->default: [1]
        Weights: all 1 (default)
        Features: none

Notice that `vertical` edges have 2 features, `horizontal` have 1, and `diagonal` have 0.

Edge weights can be specified with this multiple-DataFrames form too. Any or all of the DataFrames for an edge type can contain a `weight` column.

In [35]:
square_edges_horizontal_weighted = square_edges_horizontal.assign(weight=[12.3, 45.6])
square_edges_horizontal_weighted

  source target  A  weight
0      a      b -1    12.3
2      c      d -3    45.6

In [36]:
square_orientation_separate_weighted = StellarGraph(
    edges={
        "horizontal": square_edges_horizontal_weighted,
        "vertical": square_edges_vertical,
        "diagonal": square_edges_diagonal,
    },
)
print(square_orientation_separate_weighted.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  default: [4]
    Features: none
    Edge types: default-diagonal->default, default-horizontal->default, default-vertical->default

 Edge types:
    default-vertical->default: [2]
        Weights: all 1 (default)
        Features: float32 vector, length 2
    default-horizontal->default: [2]
        Weights: range=[12.3, 45.6], mean=28.95, std=23.5467
        Features: float32 vector, length 1
    default-diagonal->default: [1]
        Weights: all 1 (default)
        Features: none

### Multiple everything

A graph can have multiple node types and multiple edge types, with features or without, with edge weights or without and with `edge_type_column=...` (shown here) or with multiple DataFrames for edge types. We can put everything together from the previous sections to make a single complicated `StellarGraph`.

In [37]:
square_everything = StellarGraph(
    {"foo": square_foo, "bar": square_bar},
    square_edges_types_weighted,
    edge_type_column="orientation",
)
print(square_everything.info())

StellarGraph: Undirected multigraph
 Nodes: 4, Edges: 5

 Node types:
  bar: [3]
    Features: float32 vector, length 2
    Edge types: bar-diagonal->foo, bar-horizontal->bar, bar-horizontal->foo, bar-vertical->bar, bar-vertical->foo
  foo: [1]
    Features: none
    Edge types: foo-diagonal->bar, foo-horizontal->bar, foo-vertical->bar

 Edge types:
    bar-vertical->foo: [1]
        Weights: all 5.67
        Features: none
    bar-vertical->bar: [1]
        Weights: all 0.2
        Features: none
    bar-horizontal->foo: [1]
        Weights: all 1 (default)
        Features: none
    bar-horizontal->bar: [1]
        Weights: all 3.4
        Features: none
    bar-diagonal->foo: [1]
        Weights: all 1 (default)
        Features: none

### Directed heterogeneous graphs

A heterogeneous graph can be directed by using `StellarDiGraph` to construct it, similar to a homogeneous graph.

In [38]:
from stellargraph import StellarDiGraph

square_everything_directed = StellarDiGraph(
    {"foo": square_foo, "bar": square_bar},
    square_edges_types_weighted,
    edge_type_column="orientation",
)
print(square_everything_directed.info())

StellarDiGraph: Directed multigraph
 Nodes: 4, Edges: 5

 Node types:
  bar: [3]
    Features: float32 vector, length 2
    Edge types: bar-horizontal->bar, bar-vertical->bar, bar-vertical->foo
  foo: [1]
    Features: none
    Edge types: foo-diagonal->bar, foo-horizontal->bar

 Edge types:
    foo-horizontal->bar: [1]
        Weights: all 1 (default)
        Features: none
    foo-diagonal->bar: [1]
        Weights: all 1 (default)
        Features: none
    bar-vertical->foo: [1]
        Weights: all 5.67
        Features: none
    bar-vertical->bar: [1]
        Weights: all 0.2
        Features: none
    bar-horizontal->bar: [1]
        Weights: all 3.4
        Features: none

## Real data: Homogeneous graph from CSV files

We've been using a synthetic square graph with perfectly formatted data as an example for this whole notebook, because it helps us focus on just the core `StellarGraph` functionality. Real life isn't so simple; there's usually files to wrangle and formats to convert, so we'll finish this demo covering some example steps to go from data in files to a `StellarGraph`.

We'll work with the Cora dataset from <https://linqs.soe.ucsc.edu/data>:

> The Cora dataset consists of 2708 scientific publications classified into one of seven classes. The citation network consists of 5429 links. Each publication in the dataset is described by a 0/1-valued word vector indicating the absence/presence of the corresponding word from the dictionary. The dictionary consists of 1433 unique words. The README file in the dataset provides more details. 

The dataset contains two files: `cora.cites` and `cora.content`.

`cora.cites` is a tab-separated values (TSV) file of the graph edges. The first column identifies the cited paper, and the second column identifies the paper that cites it. The first three lines of the file look like:

```
35	1033
35	103482
35	103515
...
```

`cora.content` is also a TSV file of information about each node (paper), with 1435 columns: the first column is the node ID (matching the IDs used in `cora.cites`), the next 1433 are the 0/1-values of word vectors, and the last is the subject area class of the paper. The first three lines of the file look like (with the 1423 of the 0/1 columns truncated)

```
31336	0	0	...	0	1	0	0	0	0	0	0	Neural_Networks
1061127	0	0	...	1	0	0	0	0	0	0	0	Rule_Learning
1106406	0	0	...	0	0	0	0	0	0	0	0	Reinforcement_Learning
...
```

This graph is homogeneous (all nodes are papers, and all edges are citations), with node features (the 0/1-values) but no edge weights.

The StellarGraph library provides the `datasets` module ([docs](https://stellargraph.readthedocs.io/en/stable/api.html#module-stellargraph.datasets)) for working with some common datasets via classes like `Cora` ([docs](https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.datasets.Cora)). It can download the necessary files via the `download` method. (The `load` method also converts it into a `StellarGraph`, but that's too helpful for this tutorial: we're learning how to do that ourselves.)

In [6]:
from stellargraph.datasets import Cora
import os

cora = Cora()
cora.download()

# the base_directory property tells us where it was downloaded to:
cora_cites_file = os.path.join(cora.base_directory, "cora.cites")
cora_content_file = os.path.join(cora.base_directory, "cora.content")

In [40]:
cora

In [41]:
cora_cites_file

'C:\\Users\\Admin\\stellargraph-datasets\\cora\\cora.cites'

In [42]:
cora_content_file

'C:\\Users\\Admin\\stellargraph-datasets\\cora\\cora.content'

We've now got the files on disk, so we can read them using the `pd.read_csv` function. Despite the "CSV" in the name, this function can be used to read TSV files too. The files don't have a row of column headings, so we'll want to set our own.

First, the edges. We can use `source` and `target` as the column headings, to match `StellarGraph`'s defaults. However, the natural phrasing is "paper X cites paper Y", not "paper Y is cited by paper X", so we use the columns in reverse order to match.

In [43]:
cora_cites = pd.read_csv(
    cora_cites_file,
    sep="\t",  # tab-separated
    header=None,  # no heading row
    names=["target", "source"],  # set our own names for the columns
)
cora_cites

      target   source
0         35     1033
1         35   103482
2         35   103515
3         35  1050679
4         35  1103960
...      ...      ...
5424  853116    19621
5425  853116   853155
5426  853118  1140289
5427  853155   853118
5428  954315  1155073

[5429 rows x 2 columns]

In [7]:
!dir

 ’®¬ ў гбва®©бвўҐ C Ё¬ҐҐв ¬ҐвЄг Windows
 ‘ҐаЁ©­л© ­®¬Ґа в®¬ : 62C9-5265

 ‘®¤Ґа¦Ё¬®Ґ Ї ЇЄЁ C:\Users\Admin\Desktop\Decagon data

24.10.2020  15:32    <DIR>          .
24.10.2020  15:32    <DIR>          ..
24.10.2020  15:30           224я771 # ЏаҐ¤®Ўа Ў®вЄ  ¤ ­­ле (Ё§ в Ў«Ёз­ле ў Ја д®ўл© ўЁ¤) - Decagon.ipynb
24.10.2020  15:06    <DIR>          .ipynb_checkpoints
04.02.2018  08:39               266 ._bio-decagon-effectcategories.csv
04.02.2018  08:42       232я835я373 bio-decagon-combo.csv
24.10.2020  15:04        35я688я667 bio-decagon-combo.tar.gz
04.02.2018  08:39            28я152 bio-decagon-effectcategories.csv
24.10.2020  15:04             7я742 bio-decagon-effectcategories.tar.gz
04.02.2018  08:35         7я755я108 bio-decagon-mono.csv
24.10.2020  15:04         1я928я066 bio-decagon-mono.tar.gz
04.02.2018  08:35         8я503я643 bio-decagon-ppi.csv
24.10.2020  15:04         2я396я721 bio-decagon-ppi.tar.gz
17.02.2018  00:50         2я540я150 bio-decagon-targets-all.csv
24.10.2020  15:04           441я556 bio-decagon-targets-all.tar.gz
04.02.2018  08:35           360я999 bio-decagon-targets.csv
24.10.2020  15:04            61я835 bio-decagon-targets.tar.gz
24.10.2020  15:07             8я236 Untitled.ipynb
              15 д ©«®ў    292я781я285 Ў ©в
               3 Ї Ї®Є   1я921я449я984 Ў ©в бў®Ў®¤­®

In [6]:
biodecagoncombo = pd.read_csv("bio-decagon-combo.csv")
biodecagoncombo

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name
0,CID000002173,CID000003345,C0151714,hypermagnesemia
1,CID000002173,CID000003345,C0035344,retinopathy of prematurity
2,CID000002173,CID000003345,C0004144,atelectasis
3,CID000002173,CID000003345,C0002063,alkalosis
4,CID000002173,CID000003345,C0004604,Back Ache
...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis
4649438,CID000003461,CID000003954,C0043096,loss of weight
4649439,CID000003461,CID000003954,C0003962,ascites
4649440,CID000003461,CID000003954,C0038999,bulging

In [7]:
cora_cites = biodecagoncombo[["STITCH 1",'STITCH 2']]
cora_cites

             STITCH 1      STITCH 2
0        CID000002173  CID000003345
1        CID000002173  CID000003345
2        CID000002173  CID000003345
3        CID000002173  CID000003345
4        CID000002173  CID000003345
...               ...           ...
4649436  CID000003461  CID000003954
4649437  CID000003461  CID000003954
4649438  CID000003461  CID000003954
4649439  CID000003461  CID000003954
4649440  CID000003461  CID000003954

[4649441 rows x 2 columns]

In [8]:
for col in cora_cites.columns:
    cora_cites[col] = cora_cites[col].map(lambda x: x.replace('CID',''))

<ipython-input-8-efeaffec08be>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cora_cites[col] = cora_cites[col].map(lambda x: x.replace('CID',''))

In [9]:
cora_cites

          STITCH 1   STITCH 2
0        000002173  000003345
1        000002173  000003345
2        000002173  000003345
3        000002173  000003345
4        000002173  000003345
...            ...        ...
4649436  000003461  000003954
4649437  000003461  000003954
4649438  000003461  000003954
4649439  000003461  000003954
4649440  000003461  000003954

[4649441 rows x 2 columns]

In [10]:
next_features = biodecagoncombo
next_features

,STITCH 1,STITCH 2,Polypharmacy Side Effect,Side Effect Name
0,CID000002173,CID000003345,C0151714,hypermagnesemia
1,CID000002173,CID000003345,C0035344,retinopathy of prematurity
2,CID000002173,CID000003345,C0004144,atelectasis
3,CID000002173,CID000003345,C0002063,alkalosis
4,CID000002173,CID000003345,C0004604,Back Ache
...,...,...,...,...
4649436,CID000003461,CID000003954,C0149871,deep vein thromboses
4649437,CID000003461,CID000003954,C0035410,rhabdomyolysis
4649438,CID000003461,CID000003954,C0043096,loss of weight
4649439,CID000003461,CID000003954,C0003962,ascites
4649440,CID000003461,CID000003954,C0038999,bulging

In [11]:
next_features1 = next_features[["STITCH 1","Side Effect Name"]]
next_features1

             STITCH 1            Side Effect Name
0        CID000002173             hypermagnesemia
1        CID000002173  retinopathy of prematurity
2        CID000002173                 atelectasis
3        CID000002173                   alkalosis
4        CID000002173                   Back Ache
...               ...                         ...
4649436  CID000003461        deep vein thromboses
4649437  CID000003461              rhabdomyolysis
4649438  CID000003461              loss of weight
4649439  CID000003461                     ascites
4649440  CID000003461                     bulging

[4649441 rows x 2 columns]

In [12]:
next_features2 = next_features[["STITCH 2","Side Effect Name"]]
next_features2

             STITCH 2            Side Effect Name
0        CID000003345             hypermagnesemia
1        CID000003345  retinopathy of prematurity
2        CID000003345                 atelectasis
3        CID000003345                   alkalosis
4        CID000003345                   Back Ache
...               ...                         ...
4649436  CID000003954        deep vein thromboses
4649437  CID000003954              rhabdomyolysis
4649438  CID000003954              loss of weight
4649439  CID000003954                     ascites
4649440  CID000003954                     bulging

[4649441 rows x 2 columns]

In [13]:
df_merge2 = pd.merge(next_features1,next_features2, left_on = 'STITCH 1', right_on = 'STITCH 2')
df_merge2

MemoryError: Unable to allocate 409. GiB for an array with shape (54862602272,) and data type int64

In [14]:
cora_content_one_hot_subject = pd.get_dummies(
    next_features2, columns=["Side Effect Name"]
)
cora_content_one_hot_subject

MemoryError: Unable to allocate 5.70 GiB for an array with shape (1317, 4649441) and data type uint8

Now, the nodes. Again, we have to choose the columns' names. The names of the 0/1-columns don't matter so much, but we can give the first column (of IDs) and the last one (of subjects) useful names.

In [44]:
cora_feature_names = [f"w{i}" for i in range(1433)]

cora_raw_content = pd.read_csv(
    cora_content_file,
    sep="\t",  # tab-separated
    header=None,  # no heading row
    names=["id", *cora_feature_names, "subject"],  # set our own names for the columns
)
cora_raw_content

,id,w0,w1,w2,w3,w4,w5,w6,w7,w8,...,w1424,w1425,w1426,w1427,w1428,w1429,w1430,w1431,w1432,subject
0,31336,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,Neural_Networks
1,1061127,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Rule_Learning
2,1106406,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
3,13195,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
4,37879,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Probabilistic_Methods
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2703,1128975,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Genetic_Algorithms
2704,1128977,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Genetic_Algorithms
2705,1128978,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Genetic_Algorithms
2706,117328,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Case_Based
2707,24043,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Neural_Networks

In [9]:
data257 = pd.read_csv("descriptors257respiratory_SIDER_SideEffect.csv")
data257

,Unnamed: 0,SIDER_SideEffect,mol_name,nBonds,nRings,nRingAtoms,rsa,fmsaplus,fmsaminus,fsasaplus,...,com_I_3A.1,I_all_4B,I_all_4A,com_I_4A.1,I_all_5B,I_all_5A,com_I_5A.1,I_all_6B,I_all_6A,com_I_6A.1
0,0,Pneumocystis jirovecii pneumonia,0,71,4,17,1.0,0.758704,0.482213,0.758704,...,0,0,0,0,0,0,0,0,0,0
1,1,Pneumocystis jirovecii pneumonia,1,71,4,17,1.0,0.758704,0.482213,0.758704,...,0,0,0,0,0,0,0,0,0,0
2,2,Atypical pneumonia,2,126,3,12,1.0,0.839933,0.275430,0.839933,...,0,0,0,0,0,0,0,0,0,0
3,3,Community acquired pneumonia,3,126,3,12,1.0,0.840199,0.275743,0.840199,...,0,0,0,0,0,0,0,0,0,0
4,4,Community acquired pneumonia,4,40,3,14,1.0,0.637649,0.623400,0.637649,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,252,Non-small cell lung cancer,252,55,4,23,1.0,0.719666,0.539271,0.719666,...,0,0,0,0,0,0,0,0,0,0
253,253,Interstitial lung disease,253,64,5,25,1.0,0.889500,0.498131,0.889500,...,1,8,18,1,9,23,1,10,29,1
254,254,Interstitial lung disease,254,64,5,25,1.0,0.889500,0.498131,0.889500,...,1,8,18,1,9,23,1,10,29,1
255,255,Interstitial lung disease,255,58,4,23,1.0,0.738091,0.576526,0.738091,...,0,0,0,0,0,0,0,0,0,0
256,256,Interstitial lung disease,256,58,4,23,1.0,0.738091,0.576526,0.738091,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data257 = data257.drop(['Unnamed: 0'], axis = 1)
data257

,SIDER_SideEffect,mol_name,nBonds,nRings,nRingAtoms,rsa,fmsaplus,fmsaminus,fsasaplus,fsasaminus,...,com_I_3A.1,I_all_4B,I_all_4A,com_I_4A.1,I_all_5B,I_all_5A,com_I_5A.1,I_all_6B,I_all_6A,com_I_6A.1
0,Pneumocystis jirovecii pneumonia,0,71,4,17,1.0,0.758704,0.482213,0.758704,0.482213,...,0,0,0,0,0,0,0,0,0,0
1,Pneumocystis jirovecii pneumonia,1,71,4,17,1.0,0.758704,0.482213,0.758704,0.482213,...,0,0,0,0,0,0,0,0,0,0
2,Atypical pneumonia,2,126,3,12,1.0,0.839933,0.275430,0.839933,0.275430,...,0,0,0,0,0,0,0,0,0,0
3,Community acquired pneumonia,3,126,3,12,1.0,0.840199,0.275743,0.840199,0.275743,...,0,0,0,0,0,0,0,0,0,0
4,Community acquired pneumonia,4,40,3,14,1.0,0.637649,0.623400,0.637649,0.623400,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Non-small cell lung cancer,252,55,4,23,1.0,0.719666,0.539271,0.719666,0.539271,...,0,0,0,0,0,0,0,0,0,0
253,Interstitial lung disease,253,64,5,25,1.0,0.889500,0.498131,0.889500,0.498131,...,1,8,18,1,9,23,1,10,29,1
254,Interstitial lung disease,254,64,5,25,1.0,0.889500,0.498131,0.889500,0.498131,...,1,8,18,1,9,23,1,10,29,1
255,Interstitial lung disease,255,58,4,23,1.0,0.738091,0.576526,0.738091,0.576526,...,0,0,0,0,0,0,0,0,0,0
256,Interstitial lung disease,256,58,4,23,1.0,0.738091,0.576526,0.738091,0.576526,...,0,0,0,0,0,0,0,0,0,0

In [12]:
cora_content_str_subject = data257.set_index("mol_name")
cora_content_str_subject

,SIDER_SideEffect,nBonds,nRings,nRingAtoms,rsa,fmsaplus,fmsaminus,fsasaplus,fsasaminus,AbSA,...,com_I_3A.1,I_all_4B,I_all_4A,com_I_4A.1,I_all_5B,I_all_5A,com_I_5A.1,I_all_6B,I_all_6A,com_I_6A.1
mol_name,,,,,,,,,,,,,,,,,,,,,
0,Pneumocystis jirovecii pneumonia,71,4,17,1.0,0.758704,0.482213,0.758704,0.482213,0.0,...,0,0,0,0,0,0,0,0,0,0
1,Pneumocystis jirovecii pneumonia,71,4,17,1.0,0.758704,0.482213,0.758704,0.482213,0.0,...,0,0,0,0,0,0,0,0,0,0
2,Atypical pneumonia,126,3,12,1.0,0.839933,0.275430,0.839933,0.275430,0.0,...,0,0,0,0,0,0,0,0,0,0
3,Community acquired pneumonia,126,3,12,1.0,0.840199,0.275743,0.840199,0.275743,0.0,...,0,0,0,0,0,0,0,0,0,0
4,Community acquired pneumonia,40,3,14,1.0,0.637649,0.623400,0.637649,0.623400,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,Non-small cell lung cancer,55,4,23,1.0,0.719666,0.539271,0.719666,0.539271,0.0,...,0,0,0,0,0,0,0,0,0,0
253,Interstitial lung disease,64,5,25,1.0,0.889500,0.498131,0.889500,0.498131,0.0,...,1,8,18,1,9,23,1,10,29,1
254,Interstitial lung disease,64,5,25,1.0,0.889500,0.498131,0.889500,0.498131,0.0,...,1,8,18,1,9,23,1,10,29,1
255,Interstitial lung disease,58,4,23,1.0,0.738091,0.576526,0.738091,0.576526,0.0,...,0,0,0,0,0,0,0,0,0,0
256,Interstitial lung disease,58,4,23,1.0,0.738091,0.576526,0.738091,0.576526,0.0,...,0,0,0,0,0,0,0,0,0,0

As we saw above when adding node features, `StellarGraph` uses the index of the DataFrame as the connection between a node and a row of the DataFrame. Currently our dataframe just has a simple numeric range as the index, but it needs to be using the `id` column. Pandas offers [a few ways to control the indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#set-reset-index); in this case, we want to replace the current index by moving the `id` column to it, which is done most easily with `set_index`:

In [45]:
cora_content_str_subject = cora_raw_content.set_index("id")
cora_content_str_subject

,w0,w1,w2,w3,w4,w5,w6,w7,w8,w9,...,w1424,w1425,w1426,w1427,w1428,w1429,w1430,w1431,w1432,subject
id,,,,,,,,,,,,,,,,,,,,,
31336,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,Neural_Networks
1061127,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,Rule_Learning
1106406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
13195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Reinforcement_Learning
37879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Probabilistic_Methods
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128975,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Genetic_Algorithms
1128977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Genetic_Algorithms
1128978,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Genetic_Algorithms
117328,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Case_Based
24043,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Neural_Networks

We're almost ready to create the `StellarGraph`, we just have to do something about the non-numeric `subject` column. Many machine learning models only work on numeric features, requiring text and other data to be converted before apply; the models in StellarGraph are no different.

There are two options, depending on the task:

1. remove the `subject` column entirely: many uses of Cora are predicting the `subject` of a node, given all of the graph structure and other information, so including it as information in the graph is giving the answer directly
2. convert it to numeric via [one-hot](https://en.wikipedia.org/wiki/One-hot) encoding, where we have 7 columns of 0 and 1, one for each subject value (similar to the 1433 other `w...` features)

We'll look at both (feel free to skip ahead to 2).

### 1. Removing columns

Let's start with the first, removing the columns. The `drop` method ([docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)) lets us remove one or more columns.

In [46]:
cora_content_no_subject = cora_content_str_subject.drop(columns="subject")
cora_content_no_subject

,w0,w1,w2,w3,w4,w5,w6,w7,w8,w9,...,w1423,w1424,w1425,w1426,w1427,w1428,w1429,w1430,w1431,w1432
id,,,,,,,,,,,,,,,,,,,,,
31336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1061127,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1106406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128975,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1128977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1128978,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117328,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24043,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
cora_content_no_subject

,w0,w1,w2,w3,w4,w5,w6,w7,w8,w9,...,w1423,w1424,w1425,w1426,w1427,w1428,w1429,w1430,w1431,w1432
id,,,,,,,,,,,,,,,,,,,,,
31336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1061127,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1106406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
37879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128975,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1128977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1128978,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117328,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
24043,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
cora_cites

      target   source
0         35     1033
1         35   103482
2         35   103515
3         35  1050679
4         35  1103960
...      ...      ...
5424  853116    19621
5425  853116   853155
5426  853118  1140289
5427  853155   853118
5428  954315  1155073

[5429 rows x 2 columns]

We've got all the right node data, and the right edges, so now we can create a `StellarGraph` using the techniques we saw in the "homogeneous graph with features" section above.

In [49]:
cora_no_subject = StellarGraph({"paper": cora_content_no_subject}, {"cites": cora_cites})
print(cora_no_subject.info())

StellarGraph: Undirected multigraph
 Nodes: 2708, Edges: 5429

 Node types:
  paper: [2708]
    Features: float32 vector, length 1433
    Edge types: paper-cites->paper

 Edge types:
    paper-cites->paper: [5429]
        Weights: all 1 (default)
        Features: none

If we're trying to predict the subject, we'll probably need to use the `subject` labels as ground-truth labels in a supervised or semi-supervised machine learning task. This can be extracted from the DataFrame and held separately, to be passed in as training, validation or test examples.

In [50]:
cora_subject = cora_content_str_subject["subject"]
cora_subject

id
31336             Neural_Networks
1061127             Rule_Learning
1106406    Reinforcement_Learning
13195      Reinforcement_Learning
37879       Probabilistic_Methods
                    ...
1128975        Genetic_Algorithms
1128977        Genetic_Algorithms
1128978        Genetic_Algorithms
117328                 Case_Based
24043             Neural_Networks
Name: subject, Length: 2708, dtype: object

This is a normal Pandas Series, and so can be manipulated with any of the functions that support it. For example, if we wanted to train a machine learning algorithm using 25% of the nodes, we could use the `train_test_split` function ([docs](http://www.scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)) from [the scikit-learn library](https://scikit-learn.org/).

In [51]:
from sklearn import model_selection

cora_train, cora_test = model_selection.train_test_split(
    cora_subject, train_size=0.25, random_state=123
)
cora_train

id
191222            Neural_Networks
1109208        Genetic_Algorithms
308003              Rule_Learning
13205      Reinforcement_Learning
3217                       Theory
                    ...
642827      Probabilistic_Methods
1126315           Neural_Networks
1105718           Neural_Networks
3084                   Case_Based
80491             Neural_Networks
Name: subject, Length: 677, dtype: object

In [52]:
cora_test

id
1103969     Probabilistic_Methods
1119295             Rule_Learning
1130567    Reinforcement_Learning
59045                      Theory
1129494           Neural_Networks
                    ...
126867                 Case_Based
1105764    Reinforcement_Learning
782486            Neural_Networks
74821       Probabilistic_Methods
41732      Reinforcement_Learning
Name: subject, Length: 2031, dtype: object

This dataset, with this preparation, is used in [a demo of the GCN algorithm for node classification](../node-classification/gcn-node-classification.ipynb). The task is to predict the subject of each node.

### 2. One-hot encoding

Now, let's look at the other approach: converting the subjects to numeric features. The `pd.get_dummies` function ([docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html)) can do this for us, by adding extra columns (7, in this case), based on the unique values.

In [53]:
cora_content_one_hot_subject = pd.get_dummies(
    cora_content_str_subject, columns=["subject"]
)
cora_content_one_hot_subject

,w0,w1,w2,w3,w4,w5,w6,w7,w8,w9,...,w1430,w1431,w1432,subject_Case_Based,subject_Genetic_Algorithms,subject_Neural_Networks,subject_Probabilistic_Methods,subject_Reinforcement_Learning,subject_Rule_Learning,subject_Theory
id,,,,,,,,,,,,,,,,,,,,,
31336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1061127,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1106406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13195,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
37879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1128975,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1128977,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1128978,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
117328,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
24043,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [13]:
cora_content_one_hot_subject = pd.get_dummies(
    cora_content_str_subject, columns=["SIDER_SideEffect"]
)
cora_content_one_hot_subject

,nBonds,nRings,nRingAtoms,rsa,fmsaplus,fmsaminus,fsasaplus,fsasaminus,AbSA,molweight,...,SIDER_SideEffect_Non-small cell lung cancer,SIDER_SideEffect_Non-small cell lung cancer metastatic,SIDER_SideEffect_Non-small cell lung cancer stage III,SIDER_SideEffect_Nosocomial pneumonia,SIDER_SideEffect_Organising pneumonia,SIDER_SideEffect_Pneumocystis jirovecii pneumonia,SIDER_SideEffect_Small cell lung cancer,SIDER_SideEffect_Small cell lung cancer recurrent,SIDER_SideEffect_Upper respiratory tract infection,SIDER_SideEffect_Ventilator associated pneumonia
mol_name,,,,,,,,,,,,,,,,,,,,,
0,71,4,17,1.0,0.758704,0.482213,0.758704,0.482213,0.0,474.543360,...,0,0,0,0,0,1,0,0,0,0
1,71,4,17,1.0,0.758704,0.482213,0.758704,0.482213,0.0,474.543360,...,0,0,0,0,0,1,0,0,0,0
2,126,3,12,1.0,0.839933,0.275430,0.839933,0.275430,0.0,748.984480,...,0,0,0,0,0,0,0,0,0,0
3,126,3,12,1.0,0.840199,0.275743,0.840199,0.275743,0.0,748.984480,...,0,0,0,0,0,0,0,0,0,0
4,40,3,14,1.0,0.637649,0.623400,0.637649,0.623400,0.0,367.807360,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,55,4,23,1.0,0.719666,0.539271,0.719666,0.539271,0.0,450.336683,...,1,0,0,0,0,0,0,0,0,0
253,64,5,25,1.0,0.889500,0.498131,0.889500,0.498131,0.0,615.394793,...,0,0,0,0,0,0,0,0,0,0
254,64,5,25,1.0,0.889500,0.498131,0.889500,0.498131,0.0,615.394793,...,0,0,0,0,0,0,0,0,0,0
255,58,4,23,1.0,0.738091,0.576526,0.738091,0.576526,0.0,519.562410,...,0,0,0,0,0,0,0,0,0,0
256,58,4,23,1.0,0.738091,0.576526,0.738091,0.576526,0.0,519.562410,...,0,0,0,0,0,0,0,0,0,0

In [14]:
cora_content_one_hot_subject.to_csv("cora_content_one_hot_subject.csv", index=False)

Using this DataFrame, we can create a `StellarGraph` with 1440 features per node instead of 1433 like the previous section.

In [54]:
cora_one_hot_subject = StellarGraph(
    {"paper": cora_content_one_hot_subject}, {"cites": cora_cites}
)
print(cora_one_hot_subject.info())

StellarGraph: Undirected multigraph
 Nodes: 2708, Edges: 5429

 Node types:
  paper: [2708]
    Features: float32 vector, length 1440
    Edge types: paper-cites->paper

 Edge types:
    paper-cites->paper: [5429]
        Weights: all 1 (default)
        Features: none

## Conclusion

You hopefully now know more about building a `StellarGraph` in various configurations via Pandas DataFrames, including some feature preprocessing in the "Real data: Homogeneous graph from CSV files" section.

Revisit this document to use as a reminder, or [the documentation](https://stellargraph.readthedocs.io/en/stable/api.html#stellargraph.StellarGraph) for the `StellarGraph` class.

Once you've loaded your data, you can start doing machine learning: a good place to start is the [demo of the GCN algorithm on the Cora dataset for node classification](../node-classification/gcn-node-classification.ipynb). Additionally, StellarGraph includes [many other demos of other algorithms, solving other tasks](../README.md).

<table><tr><td>Run the latest release of this notebook:</td><td><a href="https://mybinder.org/v2/gh/stellargraph/stellargraph/master?urlpath=lab/tree/demos/basics/loading-pandas.ipynb" alt="Open In Binder" target="_parent"><img src="https://mybinder.org/badge_logo.svg"/></a></td><td><a href="https://colab.research.google.com/github/stellargraph/stellargraph/blob/master/demos/basics/loading-pandas.ipynb" alt="Open In Colab" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg"/></a></td></tr></table>